# version: "3.9"

# services:
#   mongodb:
#     image: mongo
#     # hostname: landrews
#     restart: always
#     container_name: mongodb
#     ports:
#       - 3005:3005
#     networks:
#       - mongo-network
#     # healthcheck:
#     #   test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u mongo -p mongo --quiet) -eq 1
#     #   interval: 10s
#     #   start_period: 30s
#     command: mongod --port 3005 --dbpath /srv/mongodb/db0 --replSet rs0 --bind_ip localhost,localhost
# networks:
#   mongo-network:
#     driver: bridge
version: "3.9"
services:
  justo-mongodb:
    container_name: justo-mongodb
    ports:
      - 3005:3005
    image: mongo:latest
    command: mongod --port=3005 --logpath /data/logs/mongolog.log --dbpath=/data/db
    volumes:
      - ./.mongodb/.logs:/data/logs
      - ./.mongodb/.data:/data/db
